#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
"""DuckDB's side of the tpc suite (run.sh).

  tpc.py prepare <kind> <sf> <dir>
      TPC-H's (h) or TPC-DS's (ds) data at scale factor <sf>, generated by
      DuckDB's tpch or tpcds extension, and what the suite needs of it:
      <dir>/data/<table>.csv, <dir>/schema.sql -- DuckDB's tables, each
      distributed as the suite distributes it -- <dir>/q/<name>.sql, the
      queries as DuckDB's extension has them, and <dir>/ref/<name>.out,
      DuckDB's answer to each, a row a line as psql -At prints one.

  tpc.py report <work> <mode>
      Each query's rows, as psql printed them under ORCA -- and under the
      planner's route, when timed -- against DuckDB's, and what
      <work>/results.tsv says of each run: a line a query, the times when
      timed, and a last line of how many passed.  Exits 1 where one did not.
      A run with parallel workers on the segments (TPC_WORKERS) is reported
      as the others, with how many times as fast each planner's queries were
      than with none and how many of ORCA's plans have a Gather.

DuckDB answers each query over the same data as the reference: the suite
copies no TPC query or answer, and the reference is right at any scale
factor.  Rows are compared as sets, a number to the cent -- DuckDB and
PostgreSQL round an average's last digits apart -- and NULL as psql prints
it, an empty field, as an empty string is.  At scale factor 1 every
answer of both matches the one DuckDB's kit ships for it (answers/sf1).
"""

import datetime
import decimal
import math
import os
import sys

# The distribution of each table: a fact table by its item or order key, so
# that a sale and its return are on one segment, a dimension by its own key;
# TPC-H's nation and region, 25 and 5 rows, replicated.
DISTRIBUTION = {
    'h': {'lineitem': 'l_orderkey', 'orders': 'o_orderkey',
          'customer': 'c_custkey', 'part': 'p_partkey',
          'partsupp': 'ps_partkey', 'supplier': 's_suppkey'},
    'ds': {'store_sales': 'ss_item_sk', 'store_returns': 'sr_item_sk',
           'catalog_sales': 'cs_item_sk', 'catalog_returns': 'cr_item_sk',
           'web_sales': 'ws_item_sk', 'web_returns': 'wr_item_sk',
           'inventory': 'inv_item_sk'},
}
REPLICATED = {'h': {'nation', 'region'}, 'ds': set()}
KIT = {'h': ('tpch', 'dbgen', 'tpch_queries', 'q%02d'),
       'ds': ('tpcds', 'dsdgen', 'tpcds_queries', '%02d')}


def value(v):
    """A value of DuckDB's as psql -At prints PostgreSQL's."""
    if v is None:
        return ''
    if isinstance(v, bool):
        return 't' if v else 'f'
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, (datetime.date, datetime.datetime)):
        return v.isoformat(sep=' ') if isinstance(v, datetime.datetime) else v.isoformat()
    return str(v)


def prepare(kind, sf, d):
    import duckdb

    ext, gen, queries, name = KIT[kind]
    config = {}
    if os.environ.get('TPC_DUCKDB_EXTENSIONS'):
        config['extension_directory'] = os.environ['TPC_DUCKDB_EXTENSIONS']
    con = duckdb.connect(config=config)
    con.execute('LOAD %s' % ext)
    con.execute('CALL %s(sf=%s)' % (gen, float(sf)))
    for sub in ('data', 'q', 'ref'):
        os.makedirs(os.path.join(d, sub), exist_ok=True)

    tables = con.execute("SELECT table_name, sql FROM duckdb_tables() ORDER BY table_name").fetchall()
    with open(os.path.join(d, 'schema.sql'), 'w') as f:
        for table, sql in tables:
            if table in REPLICATED[kind]:
                dist = 'DISTRIBUTED REPLICATED'
            else:
                key = DISTRIBUTION[kind].get(table)
                if key is None:
                    key = con.execute("SELECT column_name FROM duckdb_columns() WHERE table_name = ? "
                                      "ORDER BY column_index LIMIT 1", [table]).fetchone()[0]
                dist = 'DISTRIBUTED BY (%s)' % key
            f.write('%s %s;\n' % (sql.rstrip().rstrip(';'), dist))
            con.execute("COPY %s TO '%s' (FORMAT csv, DELIMITER '|', HEADER false, NULL '')"
                        % (table, os.path.join(d, 'data', table + '.csv')))

    for nr, query in con.execute('SELECT query_nr, query FROM %s() ORDER BY query_nr' % queries).fetchall():
        q = name % nr
        with open(os.path.join(d, 'q', q + '.sql'), 'w') as f:
            f.write(query.rstrip() + '\n')
        with open(os.path.join(d, 'ref', q + '.out'), 'w') as f:
            for row in con.execute(query).fetchall():
                f.write('|'.join(value(v) for v in row) + '\n')


def field(f):
    f = f.strip()
    if f in ('', 'NULL'):
        return ('null',)
    try:
        return ('num', decimal.Decimal(f))
    except decimal.InvalidOperation:
        return ('str', f)


def rows(path):
    try:
        with open(path, errors='replace') as f:
            return sorted((tuple(field(x) for x in line.rstrip('\n').split('|'))
                           for line in f if line.rstrip('\n') != ''), key=repr)
    except FileNotFoundError:
        return None


def same(a, b):
    """The same rows, a number to the cent."""
    if a is None or b is None or len(a) != len(b):
        return False
    key = lambda row: tuple(('num', round(v[1], 2)) if v[0] == 'num' else v for v in row)
    a, b = sorted(a, key=lambda r: repr(key(r))), sorted(b, key=lambda r: repr(key(r)))
    for x, y in zip(a, b):
        if len(x) != len(y):
            return False
        for u, v in zip(x, y):
            if u[0] == v[0] == 'num':
                if abs(u[1] - v[1]) > decimal.Decimal('0.02'):
                    return False
            elif u != v:
                return False
    return True


def report(work, mode):
    kinds = {'h': 'TPC-H', 'ds': 'TPC-DS'}
    runs = {}
    with open(os.path.join(work, 'results.tsv')) as f:
        for line in f:
            fields = line.rstrip('\n').split('\t')
            rnd, kind, q, planned, reason, oms, ost, pms, pst = fields[:9]
            w = int(fields[9]) if len(fields) > 9 else 0
            e = runs.setdefault((kind, q, w), {'planned': True, 'reason': '', 'o': [], 'p': [], 'ok': True,
                                               'gathers': fields[10] if len(fields) > 10 else '-'})
            if planned != 'yes':
                e['planned'] = False
                e['reason'] = reason
            ref = rows(os.path.join(work, kind, 'ref', q + '.out'))
            suffix = '-w%d' % w if w else ''
            for mode_, ms, st, times in (('orca', oms, ost, e['o']), ('planner', pms, pst, e['p'])):
                if st == '-':
                    continue
                times.append((int(ms), st))
                if st == 'ok' and not same(ref, rows(os.path.join(work, 'out', 'r' + rnd, '%s-%s%s-%s.out' % (kind, q, suffix, mode_)))):
                    e['ok'] = False
                    e.setdefault('wrong', set()).add(mode_)

    def best(times):
        oks = [t for t, s in times if s == 'ok']
        return (min(oks), 'ok') if oks else ((max(t for t, _ in times), times[0][1]) if times else (0, '-'))

    def gmean(xs):
        return math.exp(sum(math.log(x) for x in xs) / len(xs))

    passed = failed = 0
    for kind in ('h', 'ds'):
        for w in sorted(set(ww for (k, q, ww) in runs if k == kind)):
            items = sorted((q, e) for (k, q, ww), e in runs.items() if k == kind and ww == w)
            workers = ' with %d workers a segment' % w if w else ''
            for q, e in items:
                o, ost = best(e['o'])
                p, pst = best(e['p'])
                what = '%s %s%s' % (kinds[kind], q, workers)
                if not e['planned']:
                    problem = 'not ORCA\'s: %s' % e['reason']
                elif ost != 'ok':
                    problem = 'under ORCA: %s after %.1f s' % (ost, o / 1000)
                elif not e['ok']:
                    problem = 'rows not DuckDB\'s, %s' % ' and '.join(sorted(e.get('wrong', ())))
                else:
                    problem = None
                timing = ' (ORCA %.2f s%s%s)' % (o / 1000, (', planner %s' % ('%.2f s' % (p / 1000) if pst == 'ok' else '%s after %.0f s' % (pst, p / 1000))) if e['p'] else '',
                                                 ', %s Gathers' % e['gathers'] if w and e['gathers'] != '-' else '')
                if problem is None:
                    passed += 1
                    print('  ok     %s: ORCA\'s plan, DuckDB\'s rows%s' % (what, timing))
                else:
                    failed += 1
                    print('  NOT OK %s: %s%s' % (what, problem, timing))

            if mode == 'time':
                both = [(q, best(e['p'])[0], best(e['o'])[0]) for q, e in items
                        if e['planned'] and best(e['o'])[1] == 'ok' and best(e['p'])[1] == 'ok']
                ratios = [p / max(o, 1) for q, p, o in both]
                if ratios:
                    print('  %s%s: %d of %d ORCA\'s; where both finished, %d: planner %.1f s, ORCA %.1f s, '
                          'the planner %.2f times ORCA\'s (geometric mean); ORCA faster by a fifth in %d, slower in %d'
                          % (kinds[kind], workers, sum(1 for q, e in items if e['planned']), len(items), len(both),
                             sum(p for q, p, o in both) / 1000, sum(o for q, p, o in both) / 1000, gmean(ratios),
                             sum(1 for x in ratios if x > 1.2), sum(1 for x in ratios if x < 1 / 1.2)))
                slow = [q for q, e in items if e['p'] and best(e['p'])[1] != 'ok']
                if slow:
                    print('  %s%s: the planner\'s route did not finish %s' % (kinds[kind], workers, ' '.join(slow)))

            # against the same queries with no workers: how much faster each planner's are
            if w and (kind, items[0][0], 0) in runs:
                for mode_, key in (('ORCA', 'o'), ('the planner', 'p')):
                    pairs = [(best(runs[(kind, q, 0)][key]), best(e[key])) for q, e in items
                             if (kind, q, 0) in runs and e[key] and runs[(kind, q, 0)][key]]
                    pairs = [(a[0], b[0]) for a, b in pairs if a[1] == 'ok' and b[1] == 'ok']
                    if pairs:
                        sp = [a / max(b, 1) for a, b in pairs]
                        print('  %s%s, %s: %d queries in %.1f s, %.1f s with none: %.2f times as fast (geometric mean), '
                              'faster by a fifth in %d, slower in %d'
                              % (kinds[kind], workers, mode_, len(pairs), sum(b for a, b in pairs) / 1000,
                                 sum(a for a, b in pairs) / 1000, gmean(sp),
                                 sum(1 for x in sp if x > 1.2), sum(1 for x in sp if x < 1 / 1.2)))
                withg = [q for q, e in items if e['gathers'] not in ('-', '0')]
                print('  %s%s: ORCA\'s plan has a Gather in %d of %d' % (kinds[kind], workers, len(withg), len(items)))
    print('  %d passed, %d failed' % (passed, failed))
    return 1 if failed else 0


if __name__ == '__main__':
    if len(sys.argv) == 5 and sys.argv[1] == 'prepare':
        prepare(sys.argv[2], sys.argv[3], sys.argv[4])
    elif len(sys.argv) == 4 and sys.argv[1] == 'report':
        sys.exit(report(sys.argv[2], sys.argv[3]))
    else:
        sys.exit(__doc__)
